SRCS			= Animal.cpp \
				  Cat.cpp \
				  Dog.cpp \
				  WrongAnimal.cpp \
				  WrongCat.cpp \
				  main.cpp

OBJS			= $(SRCS:.cpp=.o)

CXX				= clang++
RM				= rm -f
CXXFLAGS		= -Wall -Wextra -Werror -I.
CPP_FLAGS		= -std=c++98

NAME			= housepets

all:			$(NAME)

$(NAME):		$(OBJS)
				$(CXX) $(CXXFLAGS) $(CPP_FLAGS) -o $(NAME) $(OBJS)

clean:
				$(RM) $(OBJS)

fclean:			clean
				$(RM) $(NAME)

re:				fclean $(NAME)

.PHONY:			all clean fclean re testR
